name = "Daniel Sobrado"
license = "MIT"
licenselink = "https://github.com/eueung/hugo-casper-two/blob/master/LICENSE.md"
description = "Daniel Sobrado's programming blog."
homepage = "https://www.danielsobrado.com/"
tags = ["spark","tensorflow","python"]
features = ["disqus", "google analytics"]
min_version=0.31

[author]
  name = "Daniel Sobrado"
  homepage = "https://www.danielsobrado.com/"

[original]
  name = "Daniel Sobrado"
  homepage = "https://www.danielsobrado.com/"
  repo = "https://github.com/TryGhost/Casper"
